sequenceiq/sultans

main.js

@martonsereg 
account details for users

User details

---

main.js

@biharitomi 
depends on https://github.com/sequenceiq/uluwatu/pull/175

CLOUD-472 added source url cookie for handling redirection

---

Dockerfile
start-docker.sh

CLOUD-472 created binary container

---

mailer.js

@lpuskas , @akanto or @doktoric

CLOUD-640 added dummy email service

---

main.js

@martonsereg 
with this change, we won't get 400 error (on load at Uluwatu) with the default user

CLOUD-643 workaround for obtaining default user details

---

main.js

CLOUD-726 on invalid state: redirect to login

---

package.json

increase version to 0.5.0

---

main.js

CLOUD-768 uaa server error check

---

main.js

@biharitomi , @akanto or @schfeca75

CLOUD-776 re-registration support

---

main.js

CLOUD-776 refresh user data on re-registration

---

main.js

CLOUD-444 added delete user function

---

main.js

CLOUD-444 default admin result set to false

---

main.js
start.sh

CLOUD-41906: use dns for service address resolving

---

main.js

CLOUD-41906: address resolving timeout can be set via envvar

---

.gitignore
Dockerfile
main.js
schema/20150421140021_create_changelog.sql
schema/20150918124357_add_new_read_scopes.sql
schema/20150921115156_add_read_scope_to_clients.sql
templates/confirmation-email.jade
templates/invite-email.jade
templates/reset-password-email.jade

CLOUD-44323 added ability to define scopes

---

main.js

Its necessary to be able to se what request are incoming.
@doktoric

access type logging added with morgan

---

mailer.js

CLOUD-46704 fixed mail sending

---

mailer.js

CLOUD-46704 tls reject

---

main.js
package.json

Apply changes that are required by upgrading UAA to 2.7.1

---

main.js

Use 'sultans.sid' for storing session in cookie, eliminate uaa session id from cookies

---

main.js

Revert 5f2ff57b90db19695412433330029d357dfa92e2

---

main.js

Use 'sultans.sid' for storing session in cookie, eliminaee uaa session id from cookies

---

main.js

CLOUD-47693 fixed user delete

---

mailer.js

More debug log
@schfeca75 @biharitomi plz review

CLOUD-50609 New user invitation email sending does not work
